services:
  auth:
    build: 
      context: .
      dockerfile: auth/Dockerfile
    entrypoint: sh auth/entrypoint.sh
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 8001:8000
    env_file:
      - .env
    # depends_on:
    #   - movie_db