services:
  auth:
    build: 
      context: .
      dockerfile: auth/Dockerfile
    entrypoint: sh auth/entrypoint.sh
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - .:/code
    ports:
      - 8001:8000
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - docs-fastapi

  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - docs-fastapi

networks:
  docs-fastapi: