"""init

Revision ID: 0db8ff54b475
Revises: 
Create Date: 2023-03-27 13:43:51.397241

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0db8ff54b475'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_artists_id', table_name='artists')
    op.drop_table('artists')
    op.drop_index('ix_songs_id', table_name='songs')
    op.drop_index('ix_songs_title', table_name='songs')
    op.drop_table('songs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('artist', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('video', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='songs_pkey')
    )
    op.create_index('ix_songs_title', 'songs', ['title'], unique=False)
    op.create_index('ix_songs_id', 'songs', ['id'], unique=False)
    op.create_table('artists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='artists_pkey')
    )
    op.create_index('ix_artists_id', 'artists', ['id'], unique=False)
    # ### end Alembic commands ###
